### ISSUE TITLE
Getting error Login Failed: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ahmethudaiaydin** [godkingjay/selenium-twitter-scraper#10]
When I did the ReadMe instructions, it returns following error: 
Get the code,
Install requirement.txt
Update env file.
Run command -> python scraper --user=@myusername --password=mypassword

```
Loading .env file
Loaded .env file


Initializing Twitter Scraper...
Setup WebDriver...
Initializing FirefoxDriver...
WebDriver Setup Complete

Logging in to Twitter...

Login Failed: 'NoneType' object is not iterable
```

**Comment by agnesmm** [comment]
Add your TWITTER_MAIL in .env :)

**Comment by ahmethudaiaydin** [comment]
My .env file looks like. 
```
TWITTER_USERNAME=ahmet.aydin@mymail.com
TWITTER_PASSWORD=******
```
And running following in cmd
`python scraper --user=@myusername --password=mypassword`

still doesn't work. Same error. Missing something?

**Comment by pierreminiggio** [comment]
> My .env file looks like.
> 
> ```
> TWITTER_USERNAME=ahmet.aydin@mymail.com
> TWITTER_PASSWORD=******
> ```
> 
> And running following in cmd `python scraper --user=@myusername --password=mypassword`
> 
> still doesn't work. Same error. Missing something?

I had the same issue, and I changed my .env for 

```
TWITTER_USERNAME=PierreMiniggio
TWITTER_MAIL=someaddress@gmail.com
TWITTER_PASSWORD=somepassword
```

and then it worked.

**Comment by ahmethudaiaydin** [comment]
@pierreminiggio, Thanks for your response. I tried and it worked for me as well!
