### ISSUE TITLE
Add examples to search for @userhandle mentions

### ISSUE THREAD

**Issue by badjoerichards** [godkingjay/selenium-twitter-scraper#2]
In the readme and examples, we have search for text, hashtags and listing posts from a user.

However, maybe include an example to **search for @userhandle mentions** as well?

That would complete the program

**Comment by godkingjay** [comment]
The program is already capable of that, you can try the "advanced search" of twitter. You can set-up an advanced query there and copy the the resulting string query and give it to the program:

Example:
1. For tweets mentioning `@elonmusk`:
```
python scraper --query="(@elonmusk)"
```

2. For tweets that mentions `@elonmusk` with atleast `1000` replies from `January 01, 2020 - August 31, 2023`:
```
python scraper --query="(@elonmusk) min_replies:1000 until:2023-08-31 since:2020-01-01"
```

![image](https://github.com/godkingjay/selenium-twitter-scraper/assets/89616705/c17ed80a-70c5-46ea-9e6c-328aab7fad92)

**Comment by badjoerichards** [comment]
Great, advanced use, thank you
