### ISSUE TITLE
(request) Allow command-line USERNAME and PASSWORD input

### ISSUE THREAD

**Issue by badjoerichards** [godkingjay/selenium-twitter-scraper#3]
python scraper -u="hello" -p="password" -t 100 -ht python --latest

This would allow users to use rotate and use different twitter accounts when scraping, preventing floods and bans.

So by default it uses the account in .env, but if provided in the command-line, will use them instead.

**Comment by godkingjay** [comment]
Actually you can just remove the USERNAME and PASSWORD variable in the .env and run the program then it will ask you to provide a username and password. But I think your ideas is to make it possible for scripts. I will definitely work on that.

**Comment by badjoerichards** [comment]
Yes, I believe that would make your program even better for use!

**Comment by godkingjay** [comment]
[feat(auth): Authentication Directly in Terminal](https://github.com/godkingjay/selenium-twitter-scraper/commit/2f078f05a86cb1ccf162c416cc515688dcd7dd5c)

[docs: Add authentication options and add sample commands for Advanced Search](https://github.com/godkingjay/selenium-twitter-scraper/commit/6f36bc33cadd071654ca6f65f102461e6d9b351a)
