### ISSUE TITLE
(request) Scrape each post/tweet [TWEET_URL], optionally [POSTER_TWITTER_ID], [TWEET_ID]

### ISSUE THREAD

**Issue by badjoerichards** [godkingjay/selenium-twitter-scraper#5]
The [TWEET_URL] is important to reference the every post/tweet that has been scraped. 
Can this be done?

Additionally, [POSTER_TWITTER_ID] and [TWEET_ID] is also useful data if possible

This should make the scraper very useful and powerful.

**Comment by godkingjay** [comment]
It's possible. However, for the [POSTER_TWITTER_ID] and [TWEET_ID] we will have to save them into a string format like this:

[POSTER_TWITTER_ID]
```
user_id:{user_id}
```

[TWEET_ID]
```
tweet_id:{tweet_id}
```

To save the full id in the csv.

commits:
[doc: update additional data 'pd' description](https://github.com/godkingjay/selenium-twitter-scraper/commit/2815f92ec7d2f67261a47476c59c9cb731d872e8)
[feat: scrape tweet link, tweet id, and user id](https://github.com/godkingjay/selenium-twitter-scraper/commit/975b5197b895ab08d8bb287cf1457af24c2a1770)
[feat(ipynb): Add tweet link, tweet id, and user id](https://github.com/godkingjay/selenium-twitter-scraper/commit/e3960dedcc69eba4dce4ca7d0a537dc67b0af587)

**Comment by badjoerichards** [comment]
This has become an incredible tool. thank you!
